# Generated by Django 5.2.1 on 2025-05-31 19:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_pedido_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metodopago',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
