# Generated by Django 5.2.1 on 2025-06-10 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_metodopago_fecha'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productocarrito',
            name='id_carrito',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='id_categoria',
        ),
        migrations.RemoveField(
            model_name='detallepedido',
            name='id_pedido',
        ),
        migrations.RemoveField(
            model_name='detallepedido',
            name='id_producto',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='id_metodo',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='metodo_pago',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='pedido',
        ),
        migrations.AlterField(
            model_name='documentomercantil',
            name='id_pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido'),
        ),
        migrations.AlterField(
            model_name='documentoconformidad',
            name='id_pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido'),
        ),
        migrations.RemoveField(
            model_name='productocarrito',
            name='id_producto',
        ),
        migrations.DeleteModel(
            name='CarritoCompras',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='DetallePedido',
        ),
        migrations.DeleteModel(
            name='MetodoPago',
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='ProductoCarrito',
        ),
    ]
