# Generated by Django 5.2.1 on 2025-06-23 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_directivo_user_operadorsistema_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentomercantil',
            name='id_pedido',
        ),
        migrations.DeleteModel(
            name='DocumentoConformidad',
        ),
        migrations.DeleteModel(
            name='DocumentoMercantil',
        ),
    ]
