# Generated by Django 5.2.1 on 2025-06-23 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedido_direccion_envio_pedido_referencia_envio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoConformidad',
            fields=[
                ('id_documento_conformidad', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_recepcion', models.DateField()),
                ('nombre_receptor', models.CharField(max_length=50)),
                ('firma_receptor', models.BooleanField()),
                ('fecha_conformidad', models.DateField()),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido')),
            ],
        ),
    ]
