# Generated by Django 5.2.1 on 2025-06-23 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0002_pedido_direccion_envio_pedido_referencia_envio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Albaran',
            fields=[
                ('id_albaran', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='albaranes/')),
                ('conforme', models.BooleanField(default=False)),
                ('comentario', models.TextField(blank=True)),
                ('fecha_conformidad', models.DateTimeField(blank=True, null=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='albaran', to='pedidos.pedido')),
            ],
        ),
    ]
