# Generated by Django 5.2.1 on 2025-06-23 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SPedidos', '0001_initial'),
        ('pedidos', '0003_documentoconformidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoMercantil',
            fields=[
                ('id_documento_mercantil', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('num_celular', models.CharField(max_length=9)),
                ('fecha_emision', models.DateField()),
                ('firma_recepcion', models.BooleanField()),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido')),
            ],
        ),
    ]
